# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('work_title', models.CharField(max_length=30)),
                ('arousement', models.IntegerField()),
            ],
        ),
    ]
