# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
    ]
