# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20190514_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='valence',
            field=models.IntegerField(default=0),
        ),
    ]
