# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 14:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_video_valence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='arousement',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='valence',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
