# Generated by Django 2.2.2 on 2019-06-13 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20190523_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='arousement',
        ),
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='valence',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='work_title',
        ),
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='Video Description', null=True, verbose_name='Video Description'),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, help_text='Video Duration', max_length=10, null=True, verbose_name='Video Duration'),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, help_text='Video Title', max_length=30, null=True, verbose_name='Video Title'),
        ),
        migrations.AddField(
            model_name='video',
            name='uri',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('start', models.CharField(blank=True, help_text='Shot Start', max_length=10, null=True, verbose_name='Shot Start')),
                ('end', models.CharField(blank=True, help_text='Shot End', max_length=10, null=True, verbose_name='Shot End')),
                ('thumbnail', models.ImageField(upload_to='')),
                ('arousal', models.IntegerField(blank=True, default=0, help_text='Shot Arousal', null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)], verbose_name='Shot Arousal')),
                ('valence', models.IntegerField(blank=True, default=0, help_text='Shot Valence', null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)], verbose_name='Shot Valence')),
                ('processed', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Video')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
    ]
