# Generated by Django 2.2.2 on 2019-06-13 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20190613_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='uri',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
