# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_video_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='shot_id',
        ),
        migrations.AlterField(
            model_name='shot',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
