# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 09:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20190620_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shot',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='shot',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
