# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20190625_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shot',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
