# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20190701_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='title',
            field=models.CharField(blank=True, help_text='Video Title', max_length=30, null=True, verbose_name='Video Title'),
        ),
    ]
