# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 15:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20190729_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='arousal',
            field=models.IntegerField(blank=True, default=0, help_text='Shot Arousal', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(-5)], verbose_name='Shot Arousal'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='valence',
            field=models.IntegerField(blank=True, default=0, help_text='Shot Valence', null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(-5)], verbose_name='Shot Valence'),
        ),
    ]
