# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 07:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20190731_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='arousal',
            field=models.IntegerField(blank=True, default=None, help_text='Shot Arousal', null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)], verbose_name='Shot Arousal'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='valence',
            field=models.IntegerField(blank=True, default=None, help_text='Shot Valence', null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(-1)], verbose_name='Shot Valence'),
        ),
    ]
