# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 10:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_annotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shot',
            old_name='arousal',
            new_name='arousal_avg',
        ),
        migrations.RenameField(
            model_name='shot',
            old_name='valence',
            new_name='valence_avg',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='start',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='title',
        ),
        migrations.AddField(
            model_name='annotation',
            name='shot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Shot'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='arousal',
            field=models.IntegerField(blank=True, default=None, help_text='Annotation Arousal', null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Annotation Arousal'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='valence',
            field=models.IntegerField(blank=True, default=None, help_text='Annotation Valence', null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Annotation Valence'),
        ),
    ]
