# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_annotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='keywords',
            field=models.CharField(blank=True, help_text='Shot Keywords', max_length=100, null=True, verbose_name='Shot Keywords'),
        ),
    ]
