# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_shot_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='keywords',
            field=models.CharField(blank=True, default=None, help_text='Shot Keywords', max_length=100, null=True, verbose_name='Shot Keywords'),
        ),
    ]
