# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_auto_20191018_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, help_text='Video Title', max_length=50, null=True, verbose_name='Video Title'),
        ),
    ]
