# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_auto_20191020_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='web_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
