# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_auto_20191027_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shot',
            name='web_uri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
