# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_auto_20191027_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='indoor',
            field=models.BooleanField(default=False),
        ),
    ]
