# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 18:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_shot_daytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='daytime',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(1)]),
        ),
    ]
