# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-31 18:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0033_auto_20191031_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='daytime',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
