# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_auto_20191101_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='nohappyfaces',
            field=models.BooleanField(default=False),
        ),
    ]
