# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 13:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_shot_nohappyfaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='pixelmotion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
