# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 15:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_shot_pixelmotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='duration',
            field=models.CharField(blank=True, help_text='Shot Duration', max_length=5, null=True, verbose_name='Shot Duration'),
        ),
        migrations.AddField(
            model_name='shot',
            name='loudness',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
