# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_auto_20191101_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='dialogue',
            field=models.BooleanField(default=False),
        ),
    ]
