# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0040_shot_dialogue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shot',
            old_name='uri',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='uri',
            new_name='filename',
        ),
        migrations.AlterField(
            model_name='shot',
            name='thumbnail',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
